Name : Priyanshi <br>
Roll no - 102497022<br>
Sub-Group - 2Q14

In [ ]:
#Q1
import numpy as np
a = np.array([1,2,3,4,5])
#(a)
b = a+2
print("After addition",b)
#(b)
c = a*3
print("After multiplication",c)
#(c)
d = a/2
print("After division",d)

After addition [3 4 5 6 7]
After multiplication [ 3  6  9 12 15]
After division [0.5 1.  1.5 2.  2.5]


In [6]:
#Q2
import numpy as np
#(a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_array = np.flip(arr)
print("Reversed array",reversed_array)

#(b)
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_val = values[counts == max_count][0]
    indices = np.where(arr == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_freq_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {most_freq_x}, Indices: {indices_x}")

most_freq_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {most_freq_y}, Indices: {indices_y}")


Reversed array [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [2]:
# Q3
import numpy as np
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
#(a)
print("Element at 1st row, 2nd column:", arr_2d[0, 1])
#(b)
print("Element at 3rd row, 1st column:", arr_2d[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [ ]:
#Q4
import numpy as np
Priyanshi = np.linspace(10, 100, 25)
print("Dimensions:", Priyanshi.ndim)
print("Shape:", Priyanshi.shape)
print("Total elements:", Priyanshi.size)
print("Data type:", Priyanshi.dtype)
print("Total bytes consumed:", Priyanshi.nbytes)
Priyanshi_transpose = Priyanshi.reshape(25, 1)
print("Transpose using reshape():\n", Priyanshi_transpose)
print("Transpose using T attribute:\n", Priyanshi.T)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [4]:
#Q5
ucs420_Priyanshi = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_Priyanshi))
print("Median:", np.median(ucs420_Priyanshi))
print("Max:", np.max(ucs420_Priyanshi))
print("Min:", np.min(ucs420_Priyanshi))
print("Unique elements:", np.unique(ucs420_Priyanshi))
reshaped_ucs420_Priyanshi = ucs420_Priyanshi.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_ucs420_Priyanshi)
resized_ucs420_Priyanshi = np.resize(ucs420_Priyanshi, (2, 3))
print("Resized (2x3):\n", resized_ucs420_Priyanshi)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
